version: "3.8"

services:
  mysql_single:
    container_name: mysql_single
    image: mysql:8.0
    env_file: ./.env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./files:/var/lib/files

volumes:
  mysql-data:
  mysql-files:
